encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/new", views.new_wiki, name="new_wiki"),
    path("wiki/random", views.random_wiki, name="random_wiki"),
    path("wiki/<str:title>/edit", views.edit_wiki, name="edit_wiki"),
    path("wiki/<str:title>", views.wiki, name="wiki"),
    # path("wiki/search/", views.search_wiki, name="search_wiki")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from django import forms


class NewWikiForm(forms.Form):
    title = forms.CharField(label='Title', max_length=100)
    content = forms.CharField(widget=forms.Textarea)

encyclopedia/views.py
import random

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .forms import NewWikiForm
from . import util
from markdown2 import Markdown


def index(request):
    if request.method == 'POST':
        query = request.POST['q']
        if util.get_entry(query):
            return HttpResponseRedirect(reverse('encyclopedia:wiki', args=[query]))
        final_entries = [entry for entry in util.list_entries() if query in entry]
        return render(request, 'encyclopedia/search.html', {
            'title': query,
            'entries': final_entries
        })


    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def wiki(request, title):
    """ Get the content of that encyclopedia title """
    if not util.get_entry(title):
        return render(request, 'encyclopedia/404.html', {
            'not_found': 'The requested page is not found!'
        })
    markdowner = Markdown()
    markdown_to_html = markdowner.convert(util.get_entry(title))
    return render(request, 'encyclopedia/entry.html', {
        'content': markdown_to_html,
        'title': title
    })



def new_wiki(request):
    """ Create a new wiki entry """
    if request.method == 'POST':
        form = NewWikiForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            if util.get_entry(title):
                return render(request, 'encyclopedia/new_wiki.html', {
                    'error': 'The new encyclopedia entry is exist!'
                })
            util.save_entry(title, content)
        else:
            return render(request, 'encyclopedia/new_wiki.html', {
                'form': form
            })

    return render(request, 'encyclopedia/new_wiki.html', {
        'form': NewWikiForm()
    })


def edit_wiki(request, title):
    """ Edit an existing wiki entry """
    if request.method == 'POST':
        new_title = request.POST['edit_title']
        new_content = request.POST['edit_content']
        util.save_entry(new_title, new_content)
        return HttpResponseRedirect(reverse('encyclopedia:wiki', args=[new_title]))
    return render(request, 'encyclopedia/edit_wiki.html', {
        'title': title,
        'entry_data': util.get_entry(title)
    })


def random_wiki(request):
    """ Get a random wiki entry from the existing list and render it. """
    random_wiki_entry = random.choice(util.list_entries())
    return render(request, 'encyclopedia/random.html', {
        'random_wiki_entry': random_wiki_entry
    })

encyclopedia/templates/encyclopedia/edit_wiki.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Edit {{ title }} wiki
{% endblock title %}

{% block body %}

    <h1>Edit this wiki</h1>
    <form action="{% url 'encyclopedia:edit_wiki' title %}" method="POST">
        {% csrf_token %}
        <input type="text" name="edit_title" value="{{ title }}">
        <textarea name="edit_content">
            {{ entry_data }}
        </textarea>
        <input type="submit" value="Save">
    </form>
{% endblock body %}

encyclopedia/templates/encyclopedia/entry.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block body %}
    {{ content|safe }}
    <br><br>
    <a href="{% url 'encyclopedia:edit_wiki' title %}">Edit this entry</a>
{% endblock body %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>
                <a href="{% url 'encyclopedia:wiki' entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_wiki' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_wiki' %}">Random Page</a> 
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new_wiki.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    New wiki
{% endblock title %}

{% block body %}
    {% if not error %}
        <form action="{% url 'encyclopedia:new_wiki' %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Save">
        </form>
    {% endif %}
    {{ error }}
{% endblock body %}

encyclopedia/templates/encyclopedia/random.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    {{ random_wiki_entry }}
{% endblock title %}

{% block body %}
    <a href="{% url 'encyclopedia:wiki' random_wiki_entry %}">{{ random_wiki_entry }}</a>
{% endblock body %}

encyclopedia/templates/encyclopedia/search.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Search result for {{ title }}
{% endblock title %}

{% block body %}
    <ul>
        {% for entry in entries %}
            <li>
                <a href="{% url 'encyclopedia:wiki' entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock body %}